"""Assemble the final README markdown from a verified draft."""

from __future__ import annotations

from .schemas import ReadmeDraft


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ").strip()


def render_readme(
    draft: ReadmeDraft,
    mermaid: str,
    *,
    has_edges: bool,
    license_name: str | None,
    commit: str | None,
    source_url: str | None,
) -> str:
    out: list[str] = [f"# {draft.title.strip()}", ""]
    if draft.tagline.strip():
        out += [f"> {draft.tagline.strip()}", ""]
    out += [draft.overview.strip(), ""]

    if draft.features:
        out += ["## Features", ""]
        out += [f"- {f.text.strip()}" for f in draft.features]
        out.append("")

    if draft.components or draft.architecture.strip():
        out += ["## Architecture", ""]
        if draft.architecture.strip():
            out += [draft.architecture.strip(), ""]
        if draft.components:
            out += ["```mermaid", mermaid, "```", ""]
            if has_edges:
                out += ["<sub>Arrows point from a component to the components it imports; labels count file-level import edges.</sub>", ""]
            out += ["| Component | Paths | Responsibility |", "| --- | --- | --- |"]
            for c in draft.components:
                paths = ", ".join(f"`{p or '/'}`" for p in c.paths)
                out.append(f"| {_cell(c.label)} | {paths} | {_cell(c.description)} |")
            out.append("")

    for heading, body in (("Installation", draft.installation), ("Usage", draft.usage)):
        if body.strip():
            out += [f"## {heading}", "", body.strip(), ""]

    if draft.configuration:
        out += ["## Configuration", "", "| Variable | Description |", "| --- | --- |"]
        out += [f"| `{_cell(c.name)}` | {_cell(c.description)} |" for c in draft.configuration]
        out.append("")

    if draft.project_structure:
        out += ["## Project structure", "", "| Path | Description |", "| --- | --- |"]
        out += [f"| `{_cell(s.path)}` | {_cell(s.description)} |" for s in draft.project_structure]
        out.append("")

    if draft.development.strip():
        out += ["## Development", "", draft.development.strip(), ""]

    if license_name:
        out += ["## License", "", f"{license_name}. See the license file in the repository root.", ""]

    stamp = f"commit {commit[:12]}" if commit else "working tree"
    origin = f" of {source_url}" if source_url else ""
    out.append(f"<!-- generated by repo2readme from {stamp}{origin} -->")
    return "\n".join(out).rstrip() + "\n"
